---
  - name: Install metricbeat  - first download
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    # Use command module
  - name: install metricbeat
    command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

    # Use copy module
  - name: drop in metricbeat config
    copy:
      src: files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

    # Use command module
  - name: enable and configure docker module for metric beat
    command: sudo /usr/bin/metricbeat modules enable docker

    # Use command module
  - name: setup metric beat
    command: sudo /usr/bin/metricbeat setup

    #    # Use command module
    #  - name: start metric beat
    #    command: service filebeat start

  - name: enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes
      masked: no
      state: started

