---
  - name: configure DVWA webserver VM with docker
    hosts: webservers
    become: true
    tasks:
    - name: install docker.io 
      apt:
        force_apt_get: yes
        update_cache: yes
        name: docker.io
        state: present

    - name: install python3-pip
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: install docker python module
      pip:
        name: docker
        state: present

    - name: download and launch a docker web container  port 80 on the host  make it restart
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        restart_policy:  always
        published_ports: 80:80

    - name: enable docker service
      systemd:
        name: docker
        enabled: yes

